name: Daily Exchange Rate

on:
  schedule:
    - cron: "10 2 * * 1-5" # UTC 02:10 = KST 11:10
  workflow_dispatch:

jobs:
  get_exchange_rate:
    runs-on: ubuntu-latest

    steps:
      - name: Get Exchange Rate
        id: get_rate
        run: |
          USD_RESPONSE=$(curl -s "https://v6.exchangerate-api.com/v6/${{ secrets.EXCHANGE_RATE_API_KEY }}/latest/USD")
          KRW_RESPONSE=$(curl -s "https://v6.exchangerate-api.com/v6/${{ secrets.EXCHANGE_RATE_API_KEY }}/latest/JPY")
          KRW_RATE=$(echo $USD_RESPONSE | jq -r '.conversion_rates.KRW')
          KRW_PER_JPY=$(echo $KRW_RESPONSE | jq -r '.conversion_rates.KRW')
          JPY_100_RATE=$(echo "scale=2; $KRW_PER_JPY * 100" | bc)
          LAST_UPDATED=$(echo $USD_RESPONSE | jq -r '.time_last_update_unix | tonumber | . + (9 * 3600) | strftime("%Y-%m-%d %H:%M:%S KST")')
          echo "krw_rate=$KRW_RATE" >> $GITHUB_OUTPUT
          echo "jpy_100_rate=$JPY_100_RATE" >> $GITHUB_OUTPUT
          echo "last_updated=$LAST_UPDATED" >> $GITHUB_OUTPUT

      - name: Send to Channel.io
        run: |
          curl -X POST "https://api.channel.io/open/v5/groups/@${{ secrets.GROUP_NAME }}/messages?botName=${{ secrets.BOT_NAME }}" \
          -H "Content-Type: application/json" \
          -H "x-access-key: ${{ secrets.CHANNEL_ACCESS_KEY }}" \
          -H "x-access-secret: ${{ secrets.CHANNEL_ACCESS_SECRET }}" \
          -d '{
            "blocks": [
              {
                "type": "text",
                "value": "<b>환율 정보</b>"
              },
              {
                "type": "text",
                "value": "• USD/KRW: ${{ steps.get_rate.outputs.krw_rate }}"
              },
              {
                "type": "text",
                "value": "• KRW/JPY: ${{ steps.get_rate.outputs.jpy_100_rate }}"
              },
              {
                "type": "text",
                "value": "(마지막 업데이트: ${{ steps.get_rate.outputs.last_updated }})"
              }
            ]
          }'
