name: Daily Exchange Rate

on:
  schedule:
    - cron: "0 2 * * 1-5"
  workflow_dispatch:

jobs:
  get_exchange_rate:
    runs-on: ubuntu-latest

    steps:
      - name: Get Exchange Rate
        id: get_rate
        run: |
          RESPONSE=$(curl -s "https://v6.exchangerate-api.com/v6/${{ secrets.EXCHANGE_RATE_API_KEY }}/latest/USD")
          RATE=$(echo $RESPONSE | jq -r '.conversion_rates.KRW')
          LAST_UPDATED=$(echo $RESPONSE | jq -r '.time_last_update_unix | tonumber | . + (9 * 3600) | strftime("%Y-%m-%d %H:%M:%S KST")')
          echo "rate=$RATE" >> $GITHUB_OUTPUT
          echo "last_updated=$LAST_UPDATED" >> $GITHUB_OUTPUT

      - name: Send to Channel.io
        run: |
          curl -X POST "https://api.channel.io/open/v5/groups/@${{ secrets.GROUP_NAME }}/messages?botName=${{ secrets.BOT_NAME }}" \
          -H "Content-Type: application/json" \
          -H "x-access-key: ${{ secrets.CHANNEL_ACCESS_KEY }}" \
          -H "x-access-secret: ${{ secrets.CHANNEL_ACCESS_SECRET }}" \
          -d '{
            "blocks": [
              {
                "type": "text",
                "value": "<b>원/달러 환율 정보</b>"
              },
              {
                "type": "text",
                "value": "오늘의 원/달러 환율은 ${{ steps.get_rate.outputs.rate }}입니다."
              },
              {
                "type": "text",
                "value": "(마지막 업데이트(한국시간): ${{ steps.get_rate.outputs.last_updated }})"
              }
            ]
          }'
